version: '3.3'

services:
  mongo:
    image: mongo:4.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: invicible
      MONGO_INITDB_ROOT_PASSWORD: property_password_321
    ports:
      - 27017:27017
    volumes:
      - ./mongo_data:/data/db
